version: '3'
services:
  backend:
    build:
      context: './backend'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - 'static:/app/static:z'
    depends_on:
      - db

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/configs:/etc/nginx/configs:ro'
      - 'static:/app/static:z'
    depends_on:
      - backend
      - db
    ports:
      - "80:80"
      - "443:443"
    restart: always

  db:
    build: './postgres'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - 'postgres_data:/var/lib/postgres/data'

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms200m -Xmx200m
      xpack.security.http.ssl.enabled: 'false'
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    expose:
      - 9200
    volumes:
    - 'elastic_data:/usr/share/elasticsearch/data'

  etl:
    build: './etl'
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      ELASTIC_HOST: http://elastic:9200
      ELASTIC_USER: $ELASTIC_USER
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      WAIT_HOSTS: elastic:9200, db:5432
    volumes:
    - $STATE_PATH:/app/state
    depends_on:
      - db
      - elastic

volumes:
  postgres_data:
  static:
  elastic_data:

